package models;

import java.util.List;

import javax.persistence.*;
import play.db.ebean.*;

@Entity public class ChallengeQuestion extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public ChallengeQuestion setId(Long id) {this.id = id; return this;}
    
    // has many FinancialInstitutionLoginChallenge
    public List<FinancialInstitutionLoginChallenge> findFinancialInstitutionLoginChallenges() {return FinancialInstitutionLoginChallenge.find.where().eq("challengeQuestionId", id).findList();}
    
    public String value; public String getValue() {return this.value;} public ChallengeQuestion setValue(String value) {this.value = value; return this;}
    
    public static ChallengeQuestion create(String value) {
        return (new ChallengeQuestion()).setValue(value).saveGet();
    }
    public ChallengeQuestion saveGet() {this.save(); return this;}
    public static Finder<Long, ChallengeQuestion> find = new Finder<Long, ChallengeQuestion>(Long.class, ChallengeQuestion.class);
}