package models;

import java.util.List;

import javax.persistence.*;
import play.db.ebean.*;

@Entity public class ChallengeAnswer extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public ChallengeAnswer setId(Long id) {this.id = id; return this;}
    
    // has many FinancialInstitutionLoginChallenge
    public List<FinancialInstitutionLoginChallenge> findFinancialInstitutionLoginChallenges() {return FinancialInstitutionLoginChallenge.find.where().eq("challengeAnswerId", id).findList();}
    
    public String value; public String getValue() {return this.value;} public ChallengeAnswer setValue(String value) {this.value = value; return this;}
    
    public static ChallengeAnswer create(String value) {
        return (new ChallengeAnswer()).setValue(value).saveGet();
    }
    public ChallengeAnswer saveGet() {this.save(); return this;}
    public static Finder<Long, ChallengeAnswer> find = new Finder<Long, ChallengeAnswer>(Long.class, ChallengeAnswer.class);
}