package models;

import java.util.List;

import javax.persistence.*;
import play.db.ebean.*;

@Entity public class FinancialInstitutionLogin extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public FinancialInstitutionLogin setId(Long id) {this.id = id; return this;}
    
    // has one User
    public String userUsername; public String getUserUsername() {return this.userUsername;} public FinancialInstitutionLogin setUserUsername(String userUsername) {this.userUsername = userUsername; return this;}
    public User findUser() {return User.find.ref(userUsername);}
    
    // has one FinancialInstitution 
    public Long financialInstitutionId; public Long getFinancialInstitutionId() {return this.financialInstitutionId;} public FinancialInstitutionLogin setFinancialInstitutionId(Long financialInstitutionId) {this.financialInstitutionId = financialInstitutionId; return this;}
    public FinancialInstitution findFinancialInstitution() {return FinancialInstitution.find.ref(financialInstitutionId);}
    
    // has many FinancialInstitutionLoginChallenge
    public List<FinancialInstitutionLoginChallenge> findFinancialInstitutionLoginChallenges() {return FinancialInstitutionLoginChallenge.find.where().eq("financialInstitutionLoginId", id).findList();}
    
    public String username; public String getUsername() {return this.username;} public FinancialInstitutionLogin setUsername(String username) {this.username = username; return this;}
    public String password; public String getPassword() {return this.password;} public FinancialInstitutionLogin setPassword(String password) {this.password = password; return this;}
    
    public static FinancialInstitutionLogin create(String userUsername, Long financialInstitutionId, String username, String password) {
        return (new FinancialInstitutionLogin()).setUserUsername(userUsername).setFinancialInstitutionId(financialInstitutionId).setUsername(username).setPassword(password).saveGet();
    }
    public FinancialInstitutionLogin saveGet() {this.save(); return this;}
    public static Finder<Long, FinancialInstitutionLogin> find = new Finder<Long, FinancialInstitutionLogin>(Long.class, FinancialInstitutionLogin.class);
}