package models;

import javax.persistence.*;
import play.db.ebean.*;

@Entity public class FinancialInstitutionLoginChallenge extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public FinancialInstitutionLoginChallenge setId(Long id) {this.id = id; return this;}
    
    // has one FinancialInstitutionLogin 
    public Long financialInstitutionLoginId; public Long getFinancialInstitutionLoginId() {return this.financialInstitutionLoginId;} public FinancialInstitutionLoginChallenge setFinancialInstitutionLoginId(Long financialInstitutionLoginId) {this.financialInstitutionLoginId = financialInstitutionLoginId; return this;}
    public FinancialInstitutionLogin findFinancialInstitutionLogin() {return FinancialInstitutionLogin.find.ref(financialInstitutionLoginId);}
    
    public String question; public String getQuestion() {return this.question;} public FinancialInstitutionLoginChallenge setQuestion(String question) {this.question = question; return this;}
    public String answer; public String getAnswer() {return this.answer;} public FinancialInstitutionLoginChallenge setAnswer(String answer) {this.answer = answer; return this;}
    
    public static FinancialInstitutionLoginChallenge create(Long financialInstitutionLoginId, String question, String answer) {
        return (new FinancialInstitutionLoginChallenge()).setFinancialInstitutionLoginId(financialInstitutionLoginId).setQuestion(question).setAnswer(answer).saveGet();
    }
    public FinancialInstitutionLoginChallenge saveGet() {this.save(); return this;}
    public static Finder<Long, FinancialInstitutionLoginChallenge> find = new Finder<Long, FinancialInstitutionLoginChallenge>(Long.class, FinancialInstitutionLoginChallenge.class);
}