package models;

import javax.persistence.*;
import play.db.ebean.*;

@Entity public class UserInterest extends Model {
    // autogenerated
    @Id public Long id; public Long getId() {return this.id;} public UserInterest setId(Long id) {this.id = id; return this;}

    // has one User
    public String userUsername; public String getUserUsername() {return this.userUsername;} public UserInterest setUserUsername(String userUsername) {this.userUsername = userUsername; return this;}
    public User findUser() {return User.find.ref(userUsername);}

    // has one Interest
    public Integer interestId; public Integer getInterestId() {return this.interestId;} public UserInterest setInterestId(Integer interestId) {this.interestId = interestId; return this;}
    public Interest findInterest() {return Interest.find.ref(interestId);}
    
	public static UserInterest create(String userUsername, Integer interestId) {
        return (new UserInterest()).setUserUsername(userUsername).setInterestId(interestId).saveGet();
    }
	public UserInterest saveGet() {this.save(); return this;}
    public static Finder<Long, UserInterest> find = new Finder<Long, UserInterest>(Long.class, UserInterest.class);
}