package models;

import java.util.*;

import javax.persistence.*;

import play.db.ebean.*;

@Entity public class UserVariable extends Model {
    // autogenerated
    @Id public Long id; public Long getId() {return this.id;} public UserVariable setId(Long id) {this.id = id; return this;}
    
	// has one User
	public String userUsername; public String getUserUsername() {return this.userUsername;} public UserVariable setUserUsername(String userUsername) {this.userUsername = userUsername; return this;}
    public User findUser() {return User.find.ref(userUsername);}
    
    public Date datePosted; public Date getDatePosted() {return datePosted;} public UserVariable setDatePosted(Date datePosted) {this.datePosted = datePosted; return this;}
    public String subcategoryCode; public String getSubcategoryCode() {return subcategoryCode;} public UserVariable setSubcategoryCode(String subcategoryCode) {this.subcategoryCode = subcategoryCode; return this;}
    public Long amount; public Long getAmount() {return amount;} public UserVariable setAmount(Long amount) {this.amount = amount; return this;}
    public Integer frequency; public Integer getFrequency() {return frequency;} public UserVariable setFrequency(Integer frequency) {this.frequency = frequency; return this;}

    public static UserVariable create(String userUsername, Date datePosted, String subcategoryCode, Long amount, Integer frequency) {
    	return (new UserVariable()).setUserUsername(userUsername).setDatePosted(datePosted).setSubcategoryCode(subcategoryCode).setAmount(amount).setFrequency(frequency).saveGet();
    }
    public UserVariable saveGet() {this.save(); return this;}
    public static Finder<String, UserVariable> find = new Finder<String, UserVariable>(String.class, UserVariable.class);
}