package models;

import javax.persistence.*;

import play.db.ebean.*;

@Entity public class VideoPayFormula extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public VideoPayFormula setId(Long id) {this.id = id; return this;}
    
    // has one Video
    public Long videoId; public Long getVideoId() {return this.videoId;} public VideoPayFormula setVideoId(Long videoId) {this.videoId = videoId; return this;}
 	public Video findVideo() {return Video.find.ref(videoId);}
 	
    public String condition; public String getCondition() {return this.condition;} public VideoPayFormula setCondition(String condition) {this.condition = condition; return this;}
    public String result; public String getResult() {return this.result;} public VideoPayFormula setResult(String result) {this.result = result; return this;}
    
    public static VideoPayFormula create(Long videoId, String condition, String result) {
    	return (new VideoPayFormula()).setVideoId(videoId).setCondition(condition).setResult(result).saveGet();
    }
    public VideoPayFormula saveGet() {this.save(); return this;}
    public static Finder<Long, VideoPayFormula> find = new Finder<Long, VideoPayFormula>(Long.class, VideoPayFormula.class);
}