package models;

import java.util.*;
import javax.persistence.*;
import play.db.ebean.*;

@Entity public class WatchedVideo extends Model {
	// autogenerated
    @Id public Long id; public Long getId() {return this.id;} public WatchedVideo setId(Long id) {this.id = id; return this;}
    
    // has one User
    @Id public String userUsername; public String getUserUsername() {return this.userUsername;} public WatchedVideo setUserUsername(String userUsername) {this.userUsername = userUsername; return this;}
    public User findUser() {return User.find.ref(userUsername);}

    // has one Video
    public Long videoId; public Long getVideoId() {return this.videoId;} public WatchedVideo setVideoId(Long videoId) {this.videoId = videoId; return this;}
 	public Video findVideo() {return Video.find.ref(videoId);}
 	
    public Calendar startTime; public Calendar getStartTime() {return this.startTime;} public WatchedVideo setStartTime(Calendar startTime) {this.startTime = startTime; return this;}
    public Calendar endTime ; public Calendar getEndTime() {return this.endTime;}public WatchedVideo setEndTime(Calendar endTime) {this.endTime = endTime; return this;}    
    public Long payout; public Long getPayout() {return this.payout;} public WatchedVideo setPayout(Long payout) {this.payout = payout; return this;}
    
    public static WatchedVideo create(String userUsername, Long videoId, Calendar startTime, Calendar endTime, Long payout) {
    	return (new WatchedVideo()).setUserUsername(userUsername).setVideoId(videoId).setStartTime(startTime).setEndTime(endTime).setPayout(payout).saveGet();
    }
    public WatchedVideo saveGet() {this.save(); return this;}
    public static Finder<Long, WatchedVideo> find = new Finder<Long, WatchedVideo>(Long.class, WatchedVideo.class);
}